version: "3"
services:
  krakend:
    # The :watch image restarts the service automatically when the configuration files change.
    # Do not use this image in production, it's meant to speed up your testing and development.
    image: devopsfaith/krakend:watch
    volumes:
      - ./config/krakend:/etc/krakend
    ports:
      - "1234:1234"
      - "8080:8080"
      - "8090:8090"
    command: ["run", "-d", "-c", "./config/krakend/krakend.json"]

  documents:
    build: documents/
    command: python ./app/documents.py
    ports:
      - "5001:5001"
    depends_on:
      - krakend

  printers:
    build: printers/
    command: python ./app/printers.py
    ports:
      - "5002:5002"
    depends_on:
      - krakend
