version: "3"
services:
  krakend:
    # The :watch image restarts the service automatically when the configuration files change.
    # Do not use this image in production, it's meant to speed up your testing and development.
    image: devopsfaith/krakend:watch
    volumes:
      - ./config/krakend:/etc/krakend
    ports:
      - "8080:8080"
    command: ["run", "-d", "-c", "/etc/krakend/krakend.json"]

  documents:
    build: documents/
    ports:
      - "5001:5001"
    depends_on:
      - krakend

  printers:
    build: printers/
    ports:
      - "5002:5002"
    depends_on:
      - krakend

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    restart: always
    ports:
      - '9080:8080'
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev