version: '3.8'
services:
  #####################
  # Book Service
  #####################
  documents:
    restart: always
    build:
      context: .
      dockerfile: ./documents/Dockerfile
    env_file: ./documents/.env
    ports:
      - "3000:3000"
    networks:
      - api-gateway

  #####################
  # Author Service
  #####################
  printers:
    restart: always
    build:
      context: .
      dockerfile: ./printers/Dockerfile
    env_file: ./printers/.env
    ports:
      - "3000:3000"
    networks:
      - api-gateway
  #####################
  # krakend Service
  #####################
  proxy:
    build:
      context: .
      
    restart: always
    ports:
      - 8080:8080
      - 8090:8090
    depends_on:
      - documents
      - printers
    networks:
      - api-gateway

networks:
  api-gateway: